# -*- encoding: utf-8 -*-
from django.conf.urls import url

from .views import (
    ContactInvoiceListView,
    ContactTimeRecordListView,
    invoice_download,
    InvoiceContactCreateView,
    InvoiceContactUpdateView,
    InvoiceDetailView,
    InvoiceDraftCreateView,
    InvoiceLineCreateView,
    InvoiceLineUpdateView,
    InvoiceListView,
    InvoicePdfUpdateView,
    InvoiceRefreshTimeRecordsUpdateView,
    InvoiceRemoveTimeRecordsUpdateView,
    InvoiceSetToDraftUpdateView,
    InvoiceTimeCreateView,
    InvoiceUpdateView,
    InvoiceUserUpdateView,
    QuickTimeRecordCreateView,
    QuickTimeRecordDeleteView,
    QuickTimeRecordListView,
    QuickTimeRecordUpdateView,
    report_invoice_time_analysis,
    report_invoice_time_analysis_csv,
    TicketTimeRecordListView,
    TimeRecordChargeableView,
    TimeRecordCreateView,
    TimeRecordListView,
    TimeRecordSummaryUserView,
    TimeRecordSummaryView,
    TimeRecordUpdateView,
    UserTimeRecordListView,
)


urlpatterns = [
    url(regex=r'^contact/(?P<pk>\d+)/create/$',
        view=InvoiceContactCreateView.as_view(),
        name='invoice.contact.create'
        ),
    url(regex=r'^contact/(?P<pk>\d+)/update/$',
        view=InvoiceContactUpdateView.as_view(),
        name='invoice.contact.update'
        ),
    url(regex=r'^contact/(?P<pk>\d+)/invoice/$',
        view=ContactInvoiceListView.as_view(),
        name='invoice.contact.list'
        ),
    url(regex=r'^contact/(?P<pk>\d+)/time/$',
        view=ContactTimeRecordListView.as_view(),
        name='invoice.time.contact.list'
        ),
    url(regex=r'^create/(?P<pk>\d+)/draft/$',
        view=InvoiceDraftCreateView.as_view(),
        name='invoice.create.draft'
        ),
    url(regex=r'^create/(?P<pk>\d+)/time/$',
        view=InvoiceTimeCreateView.as_view(),
        name='invoice.create.time'
        ),
    url(regex=r'^$',
        view=InvoiceListView.as_view(),
        name='invoice.list'
        ),
    url(regex=r'^download/(?P<pk>\d+)/$',
        view=invoice_download,
        name='invoice.download'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/$',
        view=InvoiceDetailView.as_view(),
        name='invoice.detail'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/line/create/$',
        view=InvoiceLineCreateView.as_view(),
        name='invoice.line.create'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/line/update/$',
        view=InvoiceLineUpdateView.as_view(),
        name='invoice.line.update'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/pdf/$',
        view=InvoicePdfUpdateView.as_view(),
        name='invoice.create.pdf'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/refresh-time-records/$',
        view=InvoiceRefreshTimeRecordsUpdateView.as_view(),
        name='invoice.refresh.time.records'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/remove-time-records/$',
        view=InvoiceRemoveTimeRecordsUpdateView.as_view(),
        name='invoice.remove.time.records'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/report/$',
        view=report_invoice_time_analysis,
        name='invoice.report.time.analysis'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/csv/$',
        view=report_invoice_time_analysis_csv,
        name='invoice.report.time.analysis_csv'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/set-to-draft/$',
        view=InvoiceSetToDraftUpdateView.as_view(),
        name='invoice.set.to.draft'
        ),
    url(regex=r'^invoice/(?P<pk>\d+)/update/$',
        view=InvoiceUpdateView.as_view(),
        name='invoice.update'
        ),
    # quick time record
    url(regex=r'^quick/time/record/$',
        view=QuickTimeRecordListView.as_view(),
        name='invoice.quick.time.record.list'
        ),
    url(regex=r'^quick/time/record/create/$',
        view=QuickTimeRecordCreateView.as_view(),
        name='invoice.quick.time.record.create'
        ),
    url(regex=r'^quick/time/record/(?P<pk>\d+)/update/$',
        view=QuickTimeRecordUpdateView.as_view(),
        name='invoice.quick.time.record.update'
        ),
    url(regex=r'^quick/time/record/(?P<pk>\d+)/delete/$',
        view=QuickTimeRecordDeleteView.as_view(),
        name='invoice.quick.time.record.delete'
        ),
    # settings
    url(regex=r'^user/update/$',
        view=InvoiceUserUpdateView.as_view(),
        name='invoice.user.update'
        ),
    # ticket
    url(regex=r'^ticket/(?P<pk>\d+)/time/$',
        view=TicketTimeRecordListView.as_view(),
        name='invoice.time.ticket.list'
        ),
    url(regex=r'^user/time/$',
        view=UserTimeRecordListView.as_view(),
        name='invoice.time.user.list'
        ),
    url(regex=r'^ticket/(?P<pk>\d+)/time/add/$',
        view=TimeRecordCreateView.as_view(),
        name='invoice.time.create'
        ),
    url(regex=r'^time/$',
        view=TimeRecordListView.as_view(),
        name='invoice.time'
        ),
    url(regex=r'^time/chargeable/(?P<year>\d{4})/(?P<month>\d+)/$',
        view=TimeRecordChargeableView.as_view(),
        name='invoice.time.chargeable'
        ),
    url(regex=r'^time/summary/$',
        view=TimeRecordSummaryView.as_view(),
        name='invoice.time.summary'
        ),
    url(regex=r'^time/summary/(?P<pk>\d+)/$',
        view=TimeRecordSummaryUserView.as_view(),
        name='invoice.time.summary.user'
        ),
    url(regex=r'^time/(?P<pk>\d+)/update/$',
        view=TimeRecordUpdateView.as_view(),
        name='invoice.time.update'
        ),
]
