# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0013_auto_20160415_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_time_summary', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice user',
                'verbose_name_plural': 'Invoice user',
                'ordering': ['user__username'],
            },
        ),
    ]
